### ISSUE TITLE
[Feature Request] Force stop a build and/or skip via commit message 

### ISSUE THREAD

**Issue by mirandashort** [percy/percy-web#587]
In efforts to spare my diffing limits, I want to be able to skip Percy if I quickly push another commit right after another, rebase (to continue working), or am doing a series of commits and know I won't be ready to do any validations for a bit. 

In circle, for example, if I push another commit, the previous build immediately stops running as it would be silly to keep it going since it's no longer relevant. 

I can also put `[ci skip]` in my commit message to skip all integrations, but it'd be ideal if I could choose what to skip as well (for example, I can skip [husky](https://github.com/typicode/husky) when ammending a commit that has not yet been pushed via `git commit --amend --no-verify`). Sometimes I simply forget to skip my CI, but can easily recover by going into the UI to stop. Creating a similar behavior would be extremely helpful and save me on my screenshot limits!

**Comment by fotinakis** [comment]
Thanks, we've noted this feature request.
