### ISSUE TITLE
[Feature request] Disabled projects should be at the bottom of project list 

### ISSUE THREAD

**Issue by kiwiupover** [percy/percy-web#87]
An Idea!
![image](https://cloud.githubusercontent.com/assets/647691/23769034/d6dfd49c-04c2-11e7-9f5f-3c0f0ce2c9ef.png)

**Comment by fotinakis** [comment]
Hey @kiwiupover, yeah the sorting there could use some work. That disabled project actually will move to the bottom of the list when your Dashboard project has another build and moves up (things are sorted by "updated at").

**Comment by kiwiupover** [comment]
Good to know.
